name: Build and Deploy

on:
  push:
    branches: [master]
  pull_request:

jobs:
  deploy:
    name: Deploy App

    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: |
          yarn install
          yarn images
      - name: Deploy
        run: |
          git config --global user.name "action@github.com"
          git config --global user.email "GitHub Action"
          git remote set-url origin https://${ACCESS_TOKEN}@github.com/${REPO}.git
          yarn deploy
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          REPO: ${{ github.repository }}